export const CLIENT_EVENTS = ['ROOM_CREATE','ROOM_JOIN','ROOM_LEAVE','PROFILE_UPDATE','PLAYER_READY','GAME_START','ROLE_CONFIRM','TEAM_PROPOSE','TEAM_VOTE','VOTE_RESULT_CONTINUE','QUEST_CARD','QUEST_RESULT_CONTINUE','ASSASSIN_TARGET','GAME_RESTART','CHAT_SEND'] as const;
export const SERVER_EVENTS = ['ROOM_STATE','ERROR','CHAT_MESSAGE','CHAT_HISTORY'] as const;
