export type Team = 'good' | 'evil';
export type RoleType = 'merlin' | 'percival' | 'loyal' | 'assassin' | 'morgana' | 'mordred' | 'oberon' | 'minion';
export type Phase = 'lobby' | 'role_reveal' | 'team_build' | 'team_vote' | 'vote_result' | 'quest' | 'quest_result' | 'assassination' | 'result';
export interface Player { id: string; nickname: string; sessionToken: string; socketId: string | null; role: RoleType | null; ready: boolean; connected: boolean; confirmed?: boolean; isBot?: boolean; disconnectedAt?: number | null; }
export interface RoundRecord { round: number; leaderId: string; team: string[]; votes: Record<string, boolean>; fails: number; success: boolean; }
export interface ChatMessage { id: string; playerId: string; nickname: string; text: string; at: number; }
export interface AvalonOptions { percival: boolean; morgana: boolean; mordred: boolean; oberon: boolean; }
export interface Room { roomCode: string; hostId: string; maxPlayers: number; players: Player[]; phase: Phase; options: AvalonOptions; round: number; leaderIndex: number; rejectCount: number; results: Array<'success' | 'fail'>; roundHistory: RoundRecord[]; proposedTeam: string[]; teamVotes: Record<string, boolean>; questCards: Record<string, 'success' | 'fail'>; voteResult?: { approve: number; reject: number; passed: boolean }; questResult?: { fails: number; success: boolean }; assassinTarget?: string; winner?: Team; winReason?: string; createdAt: number; updatedAt: number; lobbyExpiresAt?: number | null; allOfflineExpiresAt?: number | null; resultExpiresAt?: number | null; }
export interface PublicPlayer { id: string; nickname: string; ready: boolean; connected: boolean; isBot: boolean; isHost: boolean; hasVoted: boolean; hasQuestCard: boolean; }
export interface ClientGameState { roomCode: string; playerId: string; hostId: string; maxPlayers: number; phase: Phase; stateVersion: number; players: PublicPlayer[]; selfRole: RoleType | null; roleIntel: string[]; options: AvalonOptions; activeRoles: RoleType[]; round: number; leaderId: string | null; rejectCount: number; results: Array<'success' | 'fail'>; roundHistory: RoundRecord[]; roleConfirmedCount: number; questSize: number; proposedTeam: string[]; teamVotesCompleted: number; voteResult?: { approve: number; reject: number; passed: boolean }; revealedVotes?: Array<{ id: string; approve: boolean }>; questCardsCompleted: number; questResult?: { fails: number; success: boolean }; assassinTarget?: string; winner?: Team; winReason?: string; revealedRoles?: Array<{ id: string; role: RoleType }>; chat?: ChatMessage[]; }
export interface Ack<T = unknown> { ok: boolean; data?: T; error?: string; }
