import { describe, expect, it } from 'vitest';
import { COUNT_TABLE, type Room } from '@werewolf/shared';
import { assignRoles, clientState, doubleFail, intel, questSize } from './engine.js';
const room=(players=5):Room=>({roomCode:'ABC123',hostId:'a',maxPlayers:players,players:Array.from({length:players},(_,i)=>({id:String(i),nickname:`P${i}`,sessionToken:'x',socketId:null,role:null,ready:true,connected:true})),phase:'lobby',options:{assassin:true,assassinationAbilityRole:null,percival:true,morgana:true,mordred:false,oberon:false,revealVoteIdentities:true},round:0,leaderIndex:0,rejectCount:0,results:[],proposedTeam:[],teamVotes:{},questCards:{},createdAt:0,updatedAt:0});
describe('Avalon rules',()=>{
 it('uses the official party sizes',()=>{expect(COUNT_TABLE[5]!.quests).toEqual([2,3,2,3,3]);expect(COUNT_TABLE[10]!.evil).toBe(4);});
  it('deals one Merlin and Assassin and correct team counts',()=>{const r=room(7);assignRoles(r);expect(r.players.filter(p=>p.role==='merlin')).toHaveLength(1);expect(r.players.filter(p=>p.role==='assassin')).toHaveLength(1);expect(r.players.filter(p=>p.role&&['assassin','morgana','mordred','oberon','minion'].includes(p.role))).toHaveLength(3);});
  it('delegates the assassination ability to the configured evil role',()=>{const r=room(7);r.options={...r.options,assassin:false,assassinationAbilityRole:'morgana'};assignRoles(r);const morgana=r.players.find(player=>player.role==='morgana');expect(r.players.filter(player=>player.role==='assassin')).toHaveLength(0);expect(morgana?.hasAssassinationAbility).toBe(true);expect(r.players.filter(player=>player.hasAssassinationAbility)).toHaveLength(1);});
 it('requires two failures only in round four with 7+ players',()=>{const r=room(7);r.round=3;expect(doubleFail(r)).toBe(true);expect(questSize(r)).toBe(4);r.maxPlayers=6;expect(doubleFail(r)).toBe(false);});
 it('does not show Mordred to Merlin',()=>{const r=room();r.players[0]!.role='merlin';r.players[1]!.role='mordred';r.players[2]!.role='assassin';expect(intel(r,r.players[0]!)).toEqual(['P2님은 악의 세력입니다.']);});
 it('hides vote identities from round history when the room option is off',()=>{const r=room();r.options.revealVoteIdentities=false;r.roundHistory=[{round:0,leaderId:'0',team:['0','1'],votes:{'0':true,'1':false,'2':true,'3':false,'4':true}}];const history=clientState(r,'0').roundHistory[0]!;expect(history).toMatchObject({approveCount:3,rejectCount:2});expect(history.votes).toBeUndefined();});
 it('includes vote identities in the live result only when the room option is on',()=>{const r=room();r.phase='vote_result';r.teamVotes={'0':true,'1':false,'2':true,'3':false,'4':true};r.voteResult={approve:3,reject:2,passed:true};expect(clientState(r,'0').voteResult).toMatchObject({votes:r.teamVotes});r.options.revealVoteIdentities=false;expect(clientState(r,'0').voteResult).toEqual({approve:3,reject:2,passed:true});});
 it('includes each player avatar in public room state',()=>{const r=room();r.players[0]!.avatar='wizard';expect(clientState(r,'0').players[0]).toMatchObject({id:'0',avatar:'wizard'});});
});
