import { Fragment, useEffect, useLayoutEffect, useMemo, useRef, useState, type CSSProperties } from 'react';
import { createRoot } from 'react-dom/client';
import type { Card, CardDeclaration, CardOptions, GameConfig, PendingDecision, PlayedCard, Suit } from '@skullking/shared';
import { cardArt } from './card-art';
import { clearSession, emit, saveSession } from './socket';
import { useGame } from './store';
import './styles.css';

const suits: Record<Suit,{icon:string;name:string}>={parrot:{icon:'🦜',name:'앵무새'},map:{icon:'🗺️',name:'지도'},treasure:{icon:'💰',name:'보물'},jolly:{icon:'🏴',name:'졸리 로저'}};
const emptyCards: CardOptions={kraken:false,whale:false,loot:false,pirateAbilities:false,expansionSuitCards:false,wildMonkey:false,maryThorne:false,lastVolley:false,firstMateCon:false,stingray:false,davyJones:false,walkThePlank:false};
const fullCards: CardOptions={kraken:true,whale:true,loot:true,pirateAbilities:true,expansionSuitCards:true,wildMonkey:true,maryThorne:true,lastVolley:true,firstMateCon:true,stingray:true,davyJones:true,walkThePlank:true};
const cardSettings: Array<[keyof CardOptions,string,string]>=[
  ['kraken','Kraken','트릭을 폐기합니다.'],['whale','White Whale','숫자만 남기고 가장 높은 숫자가 이깁니다.'],['loot','Loot ×2','승자와 성공 시 +20 동맹입니다.'],['pirateAbilities','Pirate Abilities','5명의 일반 Pirate 능력을 사용합니다.'],
  ['expansionSuitCards','수트 확장 12장','7(-5), 8(+5), 0/14를 넣습니다.'],['wildMonkey','Wild Monkey 15','검정을 제외한 수트를 선언하는 15입니다.'],['maryThorne','Mary Thorne','승리 후 다음 강제 카드를 정합니다.'],
  ['lastVolley','The Last Volley','추가 한 장을 선언까지 마치고 내며 마지막 트릭을 건너뜁니다.'],['firstMateCon','First Mate Con','Pirate를 이기고, 잡은 Pirate 능력을 모두 이어서 사용합니다.'],['stingray','Spotted Stingray','숫자만 남기고 가장 낮은 숫자가 이깁니다.'],
  ['davyJones',"Davy Jones' Locker",'Sea Monster를 제거하고 한 장당 +20입니다.'],['walkThePlank','Walk the Plank','트릭의 Pirate 중 제거할 대상을 직접 고릅니다.'],
];
const icon:Record<Card['kind'],string>={number:'',wild:'🐵',pirate:'☠️',tigress:'🐯',skullKing:'💀',mermaid:'🧜',escape:'⛵',kraken:'🐙',whale:'🐋',stingray:'🛸',davy:'👻',con:'👊',lastVolley:'💥',plank:'🦈',loot:'💰'};
const label=(c:Card)=>c.kind==='number'?suits[c.suit!].name+' '+(c.isZeroFourteen?'0/14':c.rank):c.name;
const showError=(e:unknown)=>useGame.getState().setError(e instanceof Error?e.message:'요청을 처리할 수 없습니다.');
const leaveRoom=async(roomCode:string)=>{try{await emit('ROOM_LEAVE',{roomCode});}catch(e){showError(e);}finally{clearSession();useGame.getState().setGame(null);}};

const declTag=(p:PlayedCard)=>p.card.kind==='tigress'&&p.declaration?<b className={'declared-tag '+p.declaration}>{p.declaration==='pirate'?'☠ 해적':'⛵ 탈출'}</b>:(p.card.isZeroFourteen||p.card.kind==='wild')?<b className="declared-value">{p.card.kind==='wild'?(suits[p.declaration as Suit]?.icon??String(p.declaration)):String(p.declaration)}</b>:null;
type SweepCard={playerId:string;card:Card|null;declaration?:CardDeclaration;late?:boolean};
const art=(n:string)=>import.meta.env.BASE_URL+'card-art/'+n+'.jpg';
function Scene({mode}:{mode:'home'|'lobby'|'game'}){return <div className={'scene '+mode} aria-hidden="true"><div className="scene-moon"/><svg className="scene-ship" viewBox="0 0 300 260"><g fill="#03060c"><path d="M20 190q130 40 260 0l-20 30q-110 28-220 0Z"/><rect x="146" y="20" width="5" height="175"/><path d="M60 40q40 50 86 20V150Q100 170 60 140ZM152 30q60 40 90 100-40 20-90 12Z"/><rect x="76" y="90" width="3" height="100"/></g></svg>{Array.from({length:26},(_,i)=><i className="star" key={'s'+i} style={{left:(i*37)%100+'%',top:(i*53)%46+'%',animationDelay:(i%7)*.4+'s'}}/>)}{[0,1,2].map(k=><svg key={k} className={'scene-wave w'+k} viewBox="0 0 2700 200" preserveAspectRatio="none"><path d={'M0 24'+'q80-26 160 0t160 0'.repeat(17)+'V200H0Z'}/></svg>)}{Array.from({length:14},(_,i)=><i className="ember" key={'e'+i} style={{left:(i*71)%100+'%',animationDelay:(i%7)*1.3+'s',animationDuration:7+(i%5)+'s'}}/>)}</div>;}
function CardView({card,onClick,disabled,small}:{card:Card;onClick?:()=>void;disabled?:boolean;small?:boolean}) {
  const art=cardArt(card);
  return <button className={'card '+card.kind+' '+(art?'art-card ':'')+(small?'small ':'')+(disabled?'disabled':'')} onClick={onClick} disabled={disabled} title={label(card)}>
    {art?<img className="card-art" src={art} alt={label(card)} draggable={false}/>:<><span>{card.kind==='number'?suits[card.suit!].icon:icon[card.kind]}</span><b>{card.kind==='number'?card.rank:card.kind==='wild'?'15':''}</b><em>{label(card)}</em></>}
  </button>;
}
const helpTabs=['항해 규칙','서열','보너스','특수 카드','해적 능력'] as const;
function Tile({img,title,desc,tag}:{img:string;title:string;desc:string;tag?:string}){return <div className="tile"><img src={art(img)} alt={title} loading="lazy" draggable={false}/><div><b>{title}{tag&&<em>{tag}</em>}</b><p>{desc}</p></div></div>;}
function Beat({a,b,note,bonus}:{a:string;b:string;note:string;bonus:string}){return <div className="beat"><img src={art(a)} alt="" draggable={false}/><span className="beat-arrow">이긴다<i>→</i></span><img src={art(b)} alt="" draggable={false}/><div><b>{note}</b><em>{bonus}</em></div></div>;}
function Help({close}:{close:()=>void}) {
  const [tab,setTab]=useState<typeof helpTabs[number]>('항해 규칙');
  return <div className="modal" onClick={close}><div className="help book" onClick={e=>e.stopPropagation()}>
    <nav className="help-tabs">{helpTabs.map(t=><button key={t} className={t===tab?'on':''} onClick={()=>setTab(t)}>{t}</button>)}</nav>
    <div className="help-body" key={tab}>
      {tab==='항해 규칙'&&<><h2>항해 규칙</h2><ol className="steps"><li><b>딜</b>N라운드에는 N장씩 받습니다.</li><li><b>비딩</b>이번 라운드에 딸 트릭 수를 정해 <i>Yo-ho-ho!</i> 하고 동시에 공개합니다.</li><li><b>트릭</b>선(리드)부터 시계 방향으로 한 장씩 냅니다. 이긴 사람이 다음 선이 됩니다.</li><li><b>정산</b>예측이 정확하면 트릭당 <em>+20</em>, 틀리면 차이당 <em>-10</em>. 0 예측은 딜된 장수 × 10점을 걸고 성공·실패가 갈립니다.</li></ol>
        <h3>수트 따르기</h3><div className="suit-row">{[['parrot-7','앵무새'],['map-7','지도'],['treasure-7','보물'],['jolly-7','졸리 로저 · 트럼프']].map(([i,t])=><figure key={i}><img src={art(i)} alt={t} draggable={false}/><figcaption>{t}</figcaption></figure>)}</div><p className="help-note">리드 수트의 숫자 카드가 손에 있으면 그 수트를 내야 합니다. 특수 카드는 언제나 낼 수 있습니다.</p></>}
      {tab==='서열'&&<><h2>서열 · 가위바위보</h2><Beat a="skull-king" b="pirate-rosie" note="Skull King이 Pirate를 잡음" bonus="+30 / 장"/><Beat a="pirate-rosie" b="mermaid-alyra" note="Pirate가 Mermaid를 잡음" bonus="+20 / 장"/><Beat a="mermaid-alyra" b="skull-king" note="Mermaid가 Skull King을 잡음" bonus="+40"/><p className="help-note">셋이 한 트릭에 모두 나오면 <b>Mermaid</b>가 이깁니다.</p>
        <h3>기본 높낮이</h3><div className="ladder">{[['escape','Escape','항상 짐'],['parrot-9','숫자 카드','리드 수트 중 최고'],['jolly-9','졸리 로저','트럼프'],['pirate-rosie','특수 캐릭터','위 가위바위보']].map(([i,t,d],k)=><Fragment key={i}>{k>0&&<span className="lad-arrow">›</span>}<figure><img src={art(i)} alt={t} draggable={false}/><figcaption><b>{t}</b>{d}</figcaption></figure></Fragment>)}</div></>}
      {tab==='보너스'&&<><h2>보너스</h2><p className="help-note strong">보너스는 <b>예측을 맞힌 트릭 승자</b>에게만 지급됩니다.</p><div className="tiles">
        <Tile img="jolly-14" title="검정 14" desc="잡은 트릭에 있으면 +20"/><Tile img="parrot-14" title="초록·보라·노랑 14" desc="잡은 트릭에 있으면 +10"/><Tile img="skull-king" title="Skull King" desc="잡은 Pirate마다 +30"/><Tile img="mermaid-alyra" title="Mermaid" desc="Skull King을 잡으면 +40"/><Tile img="pirate-rosie" title="Pirate" desc="잡은 Mermaid마다 +20"/><Tile img="loot" title="Loot" desc="동맹이 둘 다 성공하면 각자 +20" tag="어드밴스드"/><Tile img="davy-jones" title="Davy Jones" desc="제거한 Sea Monster마다 +20" tag="확장"/><Tile img="parrot-8-expansion" title="확장 8 / 7" desc="8은 +5, 7은 -5 (확장 카드만)" tag="확장"/></div></>}
      {tab==='특수 카드'&&<><h2>특수 카드</h2><div className="tiles">
        <Tile img="tigress" title="Tigress" desc="낼 때 Pirate 또는 Escape를 선언합니다."/><Tile img="escape" title="Escape" desc="항상 집니다. 트릭을 피하고 싶을 때."/><Tile img="loot" title="Loot" desc="Escape처럼 행동하며 트릭 승자와 동맹을 맺습니다." tag="어드밴스드"/><Tile img="kraken" title="Kraken" desc="트릭을 파괴합니다. 아무도 이기지 못합니다." tag="어드밴스드"/><Tile img="white-whale" title="White Whale" desc="특수 카드를 없애고 가장 큰 숫자가 이깁니다." tag="어드밴스드"/><Tile img="spotted-stingray" title="Spotted Stingray" desc="White Whale과 같지만 가장 작은 숫자가 이깁니다." tag="확장"/><Tile img="wild-monkey-15" title="Wild Monkey 15" desc="검정을 뺀 수트를 선언하는 15." tag="확장"/><Tile img="first-mate-con" title="First Mate Con" desc="모든 Pirate를 이기지만 Mermaid·Skull King에게 집니다." tag="확장"/><Tile img="davy-jones" title="Davy Jones" desc="트릭의 Sea Monster를 모두 제거합니다." tag="확장"/><Tile img="last-volley" title="The Last Volley" desc="카드를 한 장 더 내고 마지막 트릭을 건너뜁니다." tag="확장"/><Tile img="walk-the-plank" title="Walk the Plank" desc="트릭의 Pirate 한 장을 제거합니다." tag="확장"/></div></>}
      {tab==='해적 능력'&&<><h2>해적 능력</h2><p className="help-note">트릭에 이기면 발동합니다. 쓰지 않아도 됩니다.</p><div className="tiles">
        <Tile img="pirate-rosie" title="Rosie D'Laney" desc="다음 트릭 리더를 지정합니다."/><Tile img="pirate-bendt" title="Bendt the Bandit" desc="덱에서 2장을 뽑고 2장을 버립니다."/><Tile img="pirate-rascal" title="Rascal of Roatan" desc="10점 또는 20점을 걸고 베팅합니다."/><Tile img="pirate-juanita" title="Juanita Jade" desc="남은 덱을 몰래 봅니다."/><Tile img="pirate-harry" title="Harry the Giant" desc="내 예측을 ±1 조정합니다."/><Tile img="mary-thorne" title="Mary Thorne" desc="대상의 무작위 카드를 다음 트릭에 강제로 내게 합니다." tag="확장"/></div></>}
    </div><button className="gold help-close" onClick={close}>확인</button></div></div>;
}
function Landing() {
  const [nickname,setNickname]=useState(localStorage.getItem('skullking-name')??''); const [roomCode,setRoomCode]=useState('');
  const [maxPlayers,setMaxPlayers]=useState(4); const [mode,setMode]=useState<GameConfig['roundMode']>('classic'); const [cards,setCards]=useState<CardOptions>(emptyCards); const [help,setHelp]=useState(false); const [busy,setBusy]=useState(false); const error=useGame(s=>s.error);
  const restricted=maxPlayers<3; const active=restricted?emptyCards:cards;
  const deck=70+(active.kraken?1:0)+(active.whale?1:0)+(active.loot?2:0)+(active.expansionSuitCards?12:0)+(active.wildMonkey?1:0)+(active.maryThorne?1:0)+['lastVolley','firstMateCon','stingray','davyJones','walkThePlank'].filter(k=>active[k as keyof CardOptions]).length;
  const enter=async(create:boolean)=>{try{setBusy(true);localStorage.setItem('skullking-name',nickname);const reply=await emit(create?'ROOM_CREATE':'ROOM_JOIN',create?{nickname,config:{maxPlayers,advanced:active.kraken||active.whale||active.loot,expansionSuitCards:active.expansionSuitCards,roundMode:mode,cards:active}}:{nickname,roomCode});saveSession(reply);}catch(e){showError(e);}finally{setBusy(false);}};
  const preset=(p:'classic'|'advanced'|'full')=>setCards(p==='classic'?emptyCards:p==='advanced'?{...emptyCards,kraken:true,whale:true,loot:true,pirateAbilities:true}:fullCards);
  return <main className="landing"><div className="hero"><span className="eyebrow">THE TAVERN OF SEVEN SEAS</span><h1>SKULL KING</h1><p className="subtitle">해골왕의 배에서 열리는 한 판 도박. 예측하고, 속이고, 마지막 트릭까지 살아남으세요.</p><div className="hero-cards"><img src={art("mermaid-alyra")} alt="" draggable={false}/><img src={art("skull-king")} alt="" draggable={false}/><img src={art("pirate-rosie")} alt="" draggable={false}/></div></div><section className="parchment"><label>선원 이름<input value={nickname} onChange={e=>setNickname(e.target.value)} maxLength={16}/></label><div className="columns"><div><h2>새 항해</h2>
    <label>인원 <select value={maxPlayers} onChange={e=>setMaxPlayers(Number(e.target.value))}>{[2,3,4,5,6,7,8,9].map(n=><option key={n}>{n}</option>)}</select></label>
    <label>항해 <select value={mode} onChange={e=>setMode(e.target.value as GameConfig['roundMode'])}><option value="classic">Classic · 1–10장</option><option value="evenKeeled">Even Keeled · 2,4,6,8,10장</option><option value="brawl">Skip to the Brawl · 6–10장</option><option value="swift">Swift-n-Salty · 5장 ×5</option><option value="broadside">Broadside · 10장 ×10</option><option value="whirlpool">Whirlpool · 9,7,5,3,1장 ×2</option><option value="bedtime">Past Your Bedtime · 1장</option></select></label>
    <h3>카드 상자</h3><div className="actions"><button onClick={()=>preset('classic')}>Classic</button><button onClick={()=>preset('advanced')} disabled={restricted}>Advanced</button><button className="gold" onClick={()=>preset('full')} disabled={restricted}>Full Expansion</button></div>
    {restricted?<p className="error">확장 카드·해적 능력은 3인 이상에서만 사용합니다.</p>:<div className="card-options">{cardSettings.map(([key,title,desc])=><label className="check" key={key}><input type="checkbox" checked={cards[key]} onChange={e=>setCards({...cards,[key]:e.target.checked})}/><b>{title}</b><small>{desc}</small></label>)}</div>}
    <p className="rules">현재 덱 {deck}장 · 10장 라운드 기준 최대 {Math.floor(deck/10)}명</p><button className="gold" disabled={!nickname.trim()||busy} onClick={()=>enter(true)}>방 만들기</button>
  </div><div className="join"><h2>기존 항해</h2><label>방 코드<input value={roomCode} onChange={e=>setRoomCode(e.target.value.toUpperCase())} maxLength={6}/></label><button disabled={!nickname.trim()||roomCode.length<6||busy} onClick={()=>enter(false)}>방 참가</button><button className="text" onClick={()=>setHelp(true)}>📖 게임 도움말</button></div></div>{error&&<p className="error">{error}</p>}</section>{help&&<Help close={()=>setHelp(false)}/>}</main>;
}
function BidPanel(){const game=useGame(s=>s.game)!;const [bid,setBid]=useState(0);useEffect(()=>setBid(0),[game.round]);const me=game.players.find(p=>p.id===game.playerId)!;if(me.bid!==null)return <div className="status">다른 선원들의 예측을 기다리는 중…</div>;return <div className="bid"><h2>이번 항해, 몇 트릭?</h2><div>{Array.from({length:game.cardsThisRound+1},(_,n)=><button key={n} className={bid===n?'picked':''} onClick={()=>setBid(n)}>{n}</button>)}</div><button className="gold" onClick={()=>emit('BID_SUBMIT',{roomCode:game.roomCode,bid}).catch(showError)}>✊ Yo-ho-ho! 예측 제출</button></div>;}
function Decision({pending}:{pending:PendingDecision}) {
 const game=useGame(s=>s.game)!;const [extra,setExtra]=useState<Card|null>(null);const decide=(value:string|number,declaration?:CardDeclaration)=>emit('ABILITY_DECIDE',{roomCode:game.roomCode,value,declaration}).catch(showError);const pname=(id:string)=>game.players.find(p=>p.id===id)?.nickname??id;const needsDeclaration=(card:Card)=>card.kind==='tigress'||card.kind==='wild'||card.isZeroFourteen;
 if(pending.kind==='rosieLeader'||pending.kind==='maryTarget')return <div className="modal"><div><h2>{pending.kind==='rosieLeader'?'🍲 Rosie: 다음 리더':'🗡️ Mary Thorne: 대상 선택'}</h2>{pending.options.map(id=><button key={id} onClick={()=>decide(id)}>{pname(id)}</button>)}</div></div>;
 if(pending.kind==='plankTarget'){const targets=game.trick.filter(p=>pending.options.includes(p.card.id));return <div className="modal"><div><h2>🦈 Walk the Plank</h2><p>제거할 Pirate를 고르세요.</p>{targets.map(p=><button key={p.card.id} onClick={()=>decide(p.card.id)}>{pname(p.playerId)} · {p.card.name}</button>)}</div></div>;}
 if(pending.kind==='bendtDiscard')return <div className="modal"><div><h2>🃏 Bendt: {pending.remaining}장 버리기</h2><div className="hand">{game.hand.map(c=><CardView key={c.id} card={c} onClick={()=>decide(c.id)}/>)}</div></div></div>;
 if(pending.kind==='lastVolley'){if(extra)return <div className="modal"><div><h2>💥 Last Volley 선언</h2>{extra.isZeroFourteen?<><button onClick={()=>decide(extra.id,0)}>0</button><button className="gold" onClick={()=>decide(extra.id,14)}>14</button></>:extra.kind==='wild'?<>{(['parrot','map','treasure'] as const).map(s=><button key={s} onClick={()=>decide(extra.id,s)}>{suits[s].icon} {suits[s].name}</button>)}</>:<><button className="gold" onClick={()=>decide(extra.id,'pirate')}>Pirate</button><button onClick={()=>decide(extra.id,'escape')}>Escape</button></>}<button className="text" onClick={()=>setExtra(null)}>다른 카드</button></div></div>;return <div className="modal"><div><h2>💥 Last Volley: 추가 카드</h2><div className="hand">{game.hand.map(c=><CardView key={c.id} card={c} onClick={()=>needsDeclaration(c)?setExtra(c):decide(c.id)}/>)}</div></div></div>;}
 if(pending.kind==='rascalBet')return <div className="modal"><div><h2>🎲 Rascal의 내기</h2>{[0,10,20].map(n=><button key={n} className={n===20?'gold':''} onClick={()=>decide(n)}>{n===0?'내기 안 함':n+'점 걸기'}</button>)}</div></div>;
 const myBid=game.players.find(p=>p.id===game.playerId)?.bid??0;
 return <div className="modal"><div><h2>🦍 Harry: 비드 조정</h2><p>현재 비드 {myBid} · 딜 장수 {game.cardsThisRound}</p>{[-1,0,1].filter(n=>myBid+n>=0&&myBid+n<=game.cardsThisRound).map(n=><button key={n} onClick={()=>decide(n)}>{n>0?'+1':n===0?'유지':'-1'}</button>)}</div></div>;
}
/* 첫 공개만 길게, 이후엔 짧게(몰입감 원칙) */
let seenReveal=false;
function Table(){
 const game=useGame(s=>s.game)!;const [choice,setChoice]=useState<Card|null>(null);const [help,setHelp]=useState(false);
 /* 트릭 종료 연출: 직전 상태의 트릭 카드를 복사해 두었다가 승자 칩(.sailor[data-pid]) 쪽으로 쓸어 보낸다. 승자는 '획득 수가 늘어난 선원'으로 추론(서버 상태/로직은 변경 없음). */
 const [sweep,setSweep]=useState<{cards:SweepCard[];winner:string|null;late:boolean}|null>(null);const lastOwn=useRef<SweepCard|null>(null);const prevGame=useRef(game);const sweepRef=useRef<HTMLDivElement>(null);
 /* 비딩 동시 공개: bidding → 진행 단계로 넘어가는 순간(= 전원 제출 후 서버가 공개)에 'Yo-ho-ho!' 3박 후 모든 예측을 한꺼번에 뒤집는다. 서버 로직은 그대로. */
 const [reveal,setReveal]=useState<{short:boolean;sum:number;total:number;rows:{id:string;name:string;bid:number|null;me:boolean}[]}|null>(null);const prevReveal=useRef(game);
 useEffect(()=>{const b=prevReveal.current;prevReveal.current=game;if(!b||b===game)return;if(b.phase!=='bidding'||game.phase==='bidding'||b.round!==game.round||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const rows=game.players.map(p=>({id:p.id,name:p.nickname,bid:p.bid,me:p.id===game.playerId}));const short=seenReveal;seenReveal=true;setReveal({short,sum:rows.reduce((a,r)=>a+(r.bid??0),0),total:game.cardsThisRound,rows});},[game]);
 useEffect(()=>{if(!reveal)return;const t=setTimeout(()=>setReveal(null),reveal.short?3700:4950);return()=>clearTimeout(t);},[reveal]);
 useEffect(()=>{const before=prevGame.current;prevGame.current=game;if(!before||before===game)return;const ended=before.trick.length>0&&before.round===game.round&&before.phase!=='bidding'&&game.phase!=='bidding'&&(game.trick.length<before.trick.length||game.trick[0]?.card.id!==before.trick[0].card.id);if(!ended||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;
  /* 서버가 lastTrick({cards,winnerId})을 내려주면 그것을 사용(마지막 카드까지 정확). 없으면 직전 상태 + '마지막 사람의 카드'를 보완한다: 내 카드는 직접 기억, 남의 카드는 뒷면으로 표시. */
  const last=game.lastTrick;let cards:SweepCard[]=before.trick.map(t=>({playerId:t.playerId,card:t.card,declaration:t.declaration}));
  if(last?.cards?.length&&last.cards.length>=cards.length)cards=last.cards.map(c=>({playerId:c.playerId,card:c.card,declaration:c.declaration,late:!before.trick.some(t=>t.playerId===c.playerId)}));
  else if(cards.length===before.players.length-1&&before.turnId&&!cards.some(c=>c.playerId===before.turnId)){const mine=lastOwn.current;cards.push(mine&&mine.playerId===before.turnId?{...mine,late:true}:{playerId:before.turnId,card:null,late:true});}
  const winner=last&&last.winnerId!==undefined?last.winnerId:(game.players.find(p=>p.tricks>(before.players.find(b=>b.id===p.id)?.tricks??0))?.id??null);setSweep({cards,winner,late:cards.some(c=>c.late)});},[game]);
 useEffect(()=>{if(!sweep)return;const t=setTimeout(()=>setSweep(null),sweep.late?2650:1950);return()=>clearTimeout(t);},[sweep]);
 useLayoutEffect(()=>{const root=sweepRef.current;if(!sweep||!root)return;const to=document.querySelector(`[data-pid="${sweep.winner}"]`)?.getBoundingClientRect();root.querySelectorAll<HTMLElement>('.sweep-card').forEach(el=>{const r=el.getBoundingClientRect();el.style.setProperty('--tx',(to?to.left+to.width/2-(r.left+r.width/2):0)+'px');el.style.setProperty('--ty',(to?to.top+to.height/2-(r.top+r.height/2):80)+'px');});},[sweep]);const active=game.turnId===game.playerId;const ordered=useMemo(()=>[...game.hand].sort((a,b)=>(a.suit??'z').localeCompare(b.suit??'z')+(a.rank??0)-(b.rank??0)),[game.hand]);
 const play=(card:Card,declaration?:CardDeclaration)=>{lastOwn.current={playerId:game.playerId,card,declaration};setChoice(null);emit('CARD_PLAY',{roomCode:game.roomCode,cardId:card.id,declaration}).catch(showError);};/* 차례 표시: 선(리더) · 지금/다음/N번째 · 제출 완료 */
 const bidding=game.phase==='bidding';const playedIds=new Set(game.trick.map(t=>t.playerId));const nP=game.players.length;const start=Math.max(0,game.players.findIndex(p=>p.id===(bidding?game.leaderId:game.turnId)));const waitOrder=new Map<string,number>();{let k=0;for(let j=0;j<nP;j++){const p=game.players[(start+j)%nP];if(bidding||!playedIds.has(p.id))waitOrder.set(p.id,k++);}}
 const nextUp=game.players.find(p=>!bidding&&!playedIds.has(p.id)&&waitOrder.get(p.id)===1);const nextTxt=nextUp?' · 다음은 '+nextUp.nickname:'';
 const badge=(p:{id:string})=>{const o=waitOrder.get(p.id)??0;return bidding?(o===0?'첫 리드':(o+1)+'번째'):playedIds.has(p.id)?'제출 완료':o===0?'지금 차례':o===1?'다음':(o+1)+'번째';};
 const crew=<section className="crew">{game.players.map(p=>{const o=waitOrder.get(p.id)??0;const st=bidding?(o===0?'now':'wait'):playedIds.has(p.id)?'done':o===0?'now':o===1?'next':'wait';return <div className={'sailor '+st+(game.turnId===p.id&&!bidding?' turn':'')+(game.leaderId===p.id?' leader':'')+(sweep?.winner===p.id?' collect'+(sweep.late?' late':''):'')} data-pid={p.id} key={p.id}>{game.leaderId===p.id&&<em className="lead-tag">선</em>}<b>{p.nickname}{p.id===game.playerId?' (나)':''}</b><small>{bidding?(p.bid===null?'고민 중…':'✊ 제출 완료'):(p.bid===null?'예측 대기':'예측 '+p.bid)+' · 획득 '+p.tricks}</small><strong>{p.score}점</strong><i>{p.cardsLeft}장</i><span className="order-tag">{badge(p)}</span>{sweep?.winner===p.id&&<em className="trick-plus">+1 트릭</em>}</div>;})}</section>;
 const needs=(c:Card)=>c.kind==='tigress'||c.kind==='wild'||c.isZeroFourteen;
 if(game.phase==='bidding')return <main className="game"><header><button className="leave" onClick={()=>leaveRoom(game.roomCode)}>방 나가기</button><button className="text" onClick={()=>setHelp(true)}>📖 도움말</button></header>{crew}<BidPanel/><p className="turntext">손패를 보고 이번 항해의 트릭 수를 정하세요.</p><section className="hand">{ordered.map(c=><CardView key={c.id} card={c} disabled/>)}</section>{help&&<Help close={()=>setHelp(false)}/>}</main>;
 if((game.phase==='roundScore'||game.phase==='result')&&!sweep)return <Score/>;
 return <main className="game"><header><button className="leave" onClick={()=>leaveRoom(game.roomCode)}>방 나가기</button><span>방 코드 <strong>{game.roomCode}</strong></span><span>라운드 {game.round} · {game.cardsThisRound}장</span><button className="text" onClick={()=>setHelp(true)}>📖 도움말</button></header>
 {crew}
 <section className="table"><div className="lead">{game.trickLead?suits[game.trickLead].icon+' 리드 수트':game.trick.length?'특수 카드 리드':'다음 트릭'}</div><div className="trick">{game.trick.length?game.trick.map((p:PlayedCard,i)=><div key={p.playerId+'-'+i} className={'played'+(p.card.kind==='tigress'&&p.declaration?' as-'+p.declaration:'')}><CardView card={p.card} small/>{declTag(p)}<small>{pname(game,p.playerId)}</small></div>):<div className="empty">통 위에 첫 카드를 내세요</div>}</div>{sweep&&<div className={'sweep'+(sweep.late?' has-late':'')} ref={sweepRef}>{sweep.cards.map((p,i)=><div key={i} className={'played sweep-card'+(p.playerId===sweep.winner?' win':'')+(p.late?' late':'')+(p.card?.kind==='tigress'&&p.declaration?' as-'+p.declaration:'')} style={{'--i':i} as CSSProperties}>{p.card?<><CardView card={p.card} small/>{declTag(p as unknown as PlayedCard)}</>:<div className="card small back" aria-label="마지막 카드">?</div>}<small>{pname(game,p.playerId)}</small></div>)}{!sweep.winner&&<span className="sweep-note">승자 없음 · 트릭 파괴</span>}</div>}</section>
 <p className="turntext">{active?'당신의 차례입니다.'+nextTxt:game.phase==='decision'?pname(game,game.pendingPlayerId??null)+'의 '+(game.pendingKind==='lastVolley'?'추가 카드':'능력 선택')+'을 기다리는 중…':pname(game,game.turnId)+'의 차례'+nextTxt}</p><section className="hand">{ordered.map(c=><CardView key={c.id} card={c} disabled={!active||!game.legalCardIds.includes(c.id)} onClick={()=>needs(c)?setChoice(c):play(c)}/>)}</section>
 {game.peekedDeck&&<p className="rules">🔮 Juanita가 본 남은 덱: {game.peekedDeck.map(label).join(' · ')||'없음'}</p>}
 {choice&&<div className="modal"><div>{choice.isZeroFourteen?<><h2>0/14 선언</h2><button onClick={()=>play(choice,0)}>0</button><button className="gold" onClick={()=>play(choice,14)}>14</button></>:choice.kind==='wild'?<><h2>🐵 Wild Monkey 15</h2>{(['parrot','map','treasure'] as const).map(s=><button key={s} onClick={()=>play(choice,s)}>{suits[s].icon} {suits[s].name}</button>)}</>:<><h2>🐯 Tigress 선언</h2><button className="gold" onClick={()=>play(choice,'pirate')}>Pirate</button><button onClick={()=>play(choice,'escape')}>Escape</button></>}<button className="text" onClick={()=>setChoice(null)}>취소</button></div></div>}
 {reveal&&<div className={'reveal'+(reveal.short?' short':'')} onClick={()=>setReveal(null)} role="dialog" aria-label="예측 공개"><div className="reveal-flash"/><div className="reveal-stage"><div className="reveal-title">{['Yo','ho','ho!'].map((w,k)=><span key={k} style={{'--k':k} as CSSProperties}>{w}</span>)}{[0,1,2].map(k=><i className="reveal-ring" key={k} style={{'--k':k} as CSSProperties}/>)}</div><div className="reveal-row">{reveal.rows.map((r,i)=><div className={'bid-slot'+(r.me?' me':'')+(r.bid===0?' zero':'')} key={r.id} style={{'--i':i} as CSSProperties}><div className="bid-card"><div className="bid-inner"><div className="bid-back">✊</div><div className="bid-face">{r.bid??'–'}</div></div></div><small>{r.name}{r.me?' (나)':''}</small></div>)}</div><p className="reveal-sum">예측 합계 <b>{reveal.sum}</b> · 이번 라운드 <b>{reveal.total}</b>트릭 — {reveal.sum>reveal.total?'욕심 많은 항해':reveal.sum<reveal.total?'조심스러운 항해':'정확히 맞물린 항해'}</p></div><span className="reveal-hint">탭하여 건너뛰기</span></div>} {game.pendingDecision&&<Decision pending={game.pendingDecision}/>} {help&&<Help close={()=>setHelp(false)}/>}</main>;
}
const pname=(game:NonNullable<ReturnType<typeof useGame.getState>['game']>,id:string|null)=>game?.players.find(p=>p.id===id)?.nickname??'—';
function Score(){const game=useGame(s=>s.game)!;const latest=game.history.at(-1);return <main className="game score"><header><button className="leave" onClick={()=>leaveRoom(game.roomCode)}>방 나가기</button><span>방 코드 <strong>{game.roomCode}</strong></span></header><section className="parchment"><h1>{game.phase==='result'?'👑 항해의 끝':'📜 라운드 정산'}</h1>{latest&&<table><thead><tr><th>선원</th><th>예측 / 결과</th><th>기본</th><th>보너스</th><th>누적</th></tr></thead><tbody>{latest.scores.map(r=><tr key={r.playerId}><td>{pname(game,r.playerId)}</td><td>{r.bid} / {r.tricks}</td><td>{r.base}</td><td>{r.bonus}</td><td><b>{r.total}</b></td></tr>)}</tbody></table>}{game.canAdvance&&<button className="gold" onClick={()=>emit('ROUND_ADVANCE',{roomCode:game.roomCode}).catch(showError)}>다음 항해 →</button>}</section></main>;}
function Lobby(){const game=useGame(s=>s.game)!;const me=game.players.find(p=>p.id===game.playerId)!;const host=game.hostId===game.playerId;const [help,setHelp]=useState(false);return <main className="lobby"><header><button className="leave" onClick={()=>leaveRoom(game.roomCode)}>방 나가기</button><span>방 코드 <strong>{game.roomCode}</strong></span><button className="text" onClick={()=>setHelp(true)}>📖 도움말</button></header><h1>선원 모집</h1><section className="parchment"><div className="seats">{Array.from({length:game.config.maxPlayers},(_,i)=>{const p=game.players[i];return <div className={'seat '+(p?'filled':'')} key={i}>{p?<><span>{p.isBot?'🤖':'🏴‍☠️'}</span><b>{p.nickname}</b><small>{p.ready?'준비 완료':'준비 중'}</small></>:<><span>⚓</span><small>빈 자리</small></>}</div>;})}</div><div className="actions"><button onClick={()=>emit('PLAYER_READY',{roomCode:game.roomCode}).catch(showError)}>{me.ready?'준비 취소':'준비 완료'}</button>{host&&<button onClick={()=>emit('BOT_FILL',{roomCode:game.roomCode}).catch(showError)}>봇으로 채우기</button>}{host&&<button className="gold" disabled={game.players.length<2||!game.players.every(p=>p.ready)} onClick={()=>emit('GAME_START',{roomCode:game.roomCode}).catch(showError)}>⚓ 출항!</button>}</div><p className="rules">선택된 카드: {Object.entries(game.config.cards??emptyCards).filter(([,on])=>on).map(([k])=>cardSettings.find(([id])=>id===k)?.[1]).filter(Boolean).join(' · ')||'Classic 기본 덱'}</p></section>{help&&<Help close={()=>setHelp(false)}/>}</main>;}
function App(){const game=useGame(s=>s.game);const error=useGame(s=>s.error);useEffect(()=>{if(!error)return;const timer=setTimeout(()=>useGame.getState().setError(null),3500);return()=>clearTimeout(timer);},[error]);return <><Scene mode={game?(game.phase==='lobby'?'lobby':'game'):'home'}/>{game?(game.phase==='lobby'?<Lobby/>:<Table/>):<Landing/>}{error&&game&&<div className="toast">{error}</div>}</>;}
createRoot(document.getElementById('root')!).render(<App/>);
