import { randomBytes, randomUUID } from 'node:crypto';
import type { Server,Socket } from 'socket.io';
import type { Ack,CardOptions,GameConfig,SkullRoom } from '@skullking/shared';
import { advance,createRoom,defaultCardOptions,play,resolveDecision,start,submitBid,view } from './game/engine.js';
const rooms=new Map<string,SkullRoom>();const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';const code=()=>Array.from({length:6},()=>alphabet[Math.floor(Math.random()*alphabet.length)]).join('');const token=()=>randomBytes(24).toString('base64url');const channel=(id:string)=>`skullking:player:${id}`;
const ack=<T>(socket:Socket,name:string,fn:(data:any)=>T)=>socket.on(name,(data:any,callback?:(reply:Ack<T>)=>void)=>{try{callback?.({ok:true,data:fn(data)});}catch(error){const message=error instanceof Error?error.message:'Unable to process request.';callback?.({ok:false,error:message});socket.emit('ERROR',{message});}});
function bind(socket:Socket,room:SkullRoom,playerId:string){socket.data.room=room.roomCode;socket.data.player=playerId;socket.join(channel(playerId));}
function session(socket:Socket,roomCode:string){if(socket.data.room!==roomCode||!socket.data.player)throw Error('Invalid game session.');return socket.data.player as string;}
function send(io:Server,room:SkullRoom){room.players.forEach(player=>io.to(channel(player.id)).emit('ROOM_STATE',view(room,player.id)));}
const modes=['classic','evenKeeled','brawl','swift','broadside','whirlpool','bedtime'] as const;
function configFrom(input:GameConfig):GameConfig{
  const maxPlayers=Number(input.maxPlayers);if(!Number.isInteger(maxPlayers)||maxPlayers<2||maxPlayers>9)throw Error('Choose 2 to 9 players.');
  const requested=defaultCardOptions({advanced:!!input.advanced,expansionSuitCards:!!input.expansionSuitCards,cards:input.cards});
  const cards:CardOptions=maxPlayers<3?{...requested,kraken:false,whale:false,loot:false,pirateAbilities:false,expansionSuitCards:false,wildMonkey:false,maryThorne:false,lastVolley:false,firstMateCon:false,stingray:false,davyJones:false,walkThePlank:false}:requested;
  return {maxPlayers,advanced:cards.kraken||cards.whale||cards.loot,expansionSuitCards:cards.expansionSuitCards,roundMode:modes.includes(input.roundMode as typeof modes[number])?input.roundMode:'classic',cards};
}
function settleBots(room:SkullRoom){let safety=200;while(safety-- >0){const bot=room.players.find(p=>(room.phase==='bidding'&&p.bid===null&&p.isBot)||(room.phase==='play'&&room.turnId===p.id&&p.isBot)||(room.phase==='decision'&&room.pendingDecision?.playerId===p.id&&p.isBot));if(!bot)break;
  if(room.phase==='bidding'){const strong=bot.hand.filter(c=>['skullKing','pirate','con','wild'].includes(c.kind)||(c.kind==='number'&&((c.suit==='jolly')||(c.rank??0)>=13))).length;submitBid(room,bot.id,Math.min(bot.hand.length,Math.round(strong*.45)));continue;}
  if(room.phase==='play'){const legal=view(room,bot.id).legalCardIds;const want=bot.tricks<(bot.bid??0);const card=bot.hand.filter(c=>legal.includes(c.id)).sort((a,b)=>(a.rank??0)-(b.rank??0))[want?Math.max(0,legal.length-1):0]??bot.hand[0]!;const declaration=card.kind==='tigress'?(want?'pirate':'escape'):card.isZeroFourteen?(want?14:0):card.kind==='wild'?(room.trickLead&&room.trickLead!=='jolly'?room.trickLead:'treasure'):undefined;play(room,bot.id,card.id,declaration);continue;}
  const pending=room.pendingDecision!;if(pending.kind==='rosieLeader'||pending.kind==='maryTarget')resolveDecision(room,bot.id,pending.options[0]!);else if(pending.kind==='bendtDiscard'||pending.kind==='lastVolley'){const card=bot.hand[0]!;resolveDecision(room,bot.id,card.id,card.kind==='wild'?'treasure':undefined);}else if(pending.kind==='rascalBet')resolveDecision(room,bot.id,0);else resolveDecision(room,bot.id,0);
}}
export function registerHandlers(io:Server,socket:Socket){
  ack(socket,'ROOM_CREATE',data=>{const nickname=String(data.nickname??'').trim().slice(0,16);if(!nickname)throw Error('Enter a nickname.');const config=configFrom(data.config as GameConfig);let roomCode=code();while(rooms.has(roomCode))roomCode=code();const playerId=randomUUID();const room=createRoom(roomCode,playerId,nickname,config,token());room.players[0]!.socketId=socket.id;rooms.set(roomCode,room);bind(socket,room,playerId);send(io,room);return {roomCode,playerId,sessionToken:room.players[0]!.sessionToken};});
  ack(socket,'ROOM_JOIN',data=>{const room=rooms.get(String(data.roomCode??'').toUpperCase());if(!room)throw Error('Room not found.');let sailor=room.players.find(p=>p.id===data.playerId&&p.sessionToken===data.sessionToken);if(sailor){sailor.socketId=socket.id;sailor.connected=true;}else{if(room.phase!=='lobby'||room.players.length>=room.config.maxPlayers)throw Error('This room cannot be joined.');const nickname=String(data.nickname??'').trim().slice(0,16);if(!nickname||room.players.some(p=>p.nickname===nickname))throw Error('Choose a different nickname.');sailor={id:randomUUID(),nickname,sessionToken:token(),socketId:socket.id,connected:true,ready:false,isBot:false,hand:[],bid:null,tricks:0,score:0,roundBonus:0};room.players.push(sailor);}bind(socket,room,sailor.id);send(io,room);return {roomCode:room.roomCode,playerId:sailor.id,sessionToken:sailor.sessionToken};});
  ack(socket,'BOT_FILL',data=>{const room=rooms.get(String(data.roomCode??'').toUpperCase());if(!room||room.hostId!==session(socket,room?.roomCode??'')||room.phase!=='lobby')throw Error('Only the captain can fill the lobby.');while(room.players.length<room.config.maxPlayers){const number=room.players.filter(p=>p.isBot).length+1;room.players.push({id:randomUUID(),nickname:`Deckhand ${number}`,sessionToken:'',socketId:null,connected:true,ready:true,isBot:true,hand:[],bid:null,tricks:0,score:0,roundBonus:0});}send(io,room);return {};});
  ack(socket,'PLAYER_READY',data=>{const room=rooms.get(String(data.roomCode??'').toUpperCase());if(!room||room.phase!=='lobby')throw Error('Ready is only available in the lobby.');const sailor=room.players.find(p=>p.id===session(socket,room.roomCode))!;sailor.ready=!sailor.ready;send(io,room);return {};});
  const mutate=(event:string,fn:(room:SkullRoom,actor:string,data:any)=>void)=>ack(socket,event,data=>{const room=rooms.get(String(data.roomCode??'').toUpperCase());if(!room)throw Error('Room not found.');fn(room,session(socket,room.roomCode),data);settleBots(room);send(io,room);return {};});
  mutate('GAME_START',(room,actor)=>start(room,actor));mutate('BID_SUBMIT',(room,actor,data)=>submitBid(room,actor,Number(data.bid)));mutate('CARD_PLAY',(room,actor,data)=>play(room,actor,String(data.cardId),data.declaration));mutate('ABILITY_DECIDE',(room,actor,data)=>resolveDecision(room,actor,data.value,data.declaration));mutate('ROUND_ADVANCE',(room,actor)=>advance(room,actor));
  socket.on('disconnect',()=>{const room=rooms.get(socket.data.room);const sailor=room?.players.find(p=>p.id===socket.data.player);if(sailor&&sailor.socketId===socket.id){sailor.connected=false;sailor.socketId=null;if(room)send(io,room);}});
}
