import { randomBytes, randomUUID } from 'node:crypto';
import type { Server, Socket } from 'socket.io';
import type { Ack, BloodBoundAction, BloodBoundRoom } from '@bloodbound/shared';
import { createRoom, reduce } from '../game/engine.js';
import { settleBots } from '../game/bots.js';
import { clientState } from '../game/view.js';
import { deleteRoom, getRoom, saveRoom, withRoomLock } from '../services/rooms.js';

const code=()=>Array.from({length:6},()=> 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[Math.floor(Math.random()*32)]).join('');
const token=()=>randomBytes(24).toString('base64url');const channel=(id:string)=>`bloodbound:player:${id}`;const roomChannel=(id:string)=>`bloodbound:room:${id}`;
const botEquipment=()=>({shields:[] as string[],swords:[] as string[],staffs:0,fans:0,quill:false});
const pendingBotDecisions=new Set<string>();
const ack=<T>(socket:Socket,name:string,fn:(data:any)=>Promise<T>)=>socket.on(name,async(data:any,callback?:(reply:Ack<T>)=>void)=>{try{callback?.({ok:true,data:await fn(data)});}catch(error){const message=error instanceof Error?error.message:'요청을 처리하지 못했습니다.';callback?.({ok:false,error:message});socket.emit('ERROR',{message});}});
function bind(socket:Socket,room:BloodBoundRoom,playerId:string){socket.data.roomCode=room.roomCode;socket.data.playerId=playerId;socket.join(channel(playerId));socket.join(roomChannel(room.roomCode));}
function session(socket:Socket,code:string){if(socket.data.roomCode!==code||!socket.data.playerId)throw Error('유효한 게임 세션이 아닙니다.');return socket.data.playerId as string;}
export async function emitRoomState(io:Server,room:BloodBoundRoom){for(const player of room.players)io.to(channel(player.id)).emit('ROOM_STATE',clientState(room,player.id));scheduleBotDecision(io,room);}
function scheduleBotDecision(io:Server,room:BloodBoundRoom){
  const targetId=room.attack?.targetId;const target=targetId?room.players.find(player=>player.id===targetId):undefined;
  if(!target?.isBot||!['intervention_offer','intervention_decide'].includes(room.phase)||pendingBotDecisions.has(room.roomCode))return;
  pendingBotDecisions.add(room.roomCode);
  setTimeout(()=>void (async()=>{
    let next:BloodBoundRoom|null=null;
    try {
      next=await withRoomLock(room.roomCode,async current=>{
        const target=current.attack?.targetId?current.players.find(player=>player.id===current.attack!.targetId):undefined;
        if(!target?.isBot||!['intervention_offer','intervention_decide'].includes(current.phase))return null;
        const intervenerId=current.attack?.offers.find(id=>current.players.find(player=>player.id===id)?.isBot);
        const result=reduce(current,{type:'INTERVENE_DECIDE',actorId:target.id,intervenerId});
        if('error' in result)return null;
        const settled=settleBots(result.state);await saveRoom(settled);return settled;
      });
    } catch { /* a human already resolved the attack */ }
    finally { pendingBotDecisions.delete(room.roomCode); }
    if(next){await emitRoomState(io,next);scheduleBotDecision(io,next);}
  })(),900);
}
export function registerHandlers(io:Server,socket:Socket){
  ack(socket,'ROOM_CREATE',async(data)=>{const maxPlayers=Number(data.maxPlayers);if(!Number.isInteger(maxPlayers)||maxPlayers<6||maxPlayers>12)throw Error('인원은 6~12명이어야 합니다.');const nickname=String(data.nickname??'').trim().slice(0,16);if(!nickname)throw Error('닉네임을 입력하세요.');let roomCode=code();while(await getRoom(roomCode))roomCode=code();const playerId=randomUUID();const room=createRoom(roomCode,playerId,nickname,maxPlayers,Number(data.seed)||Date.now(),token());room.players[0]!.socketId=socket.id;await saveRoom(room);bind(socket,room,playerId);await emitRoomState(io,room);return {roomCode,playerId,sessionToken:room.players[0]!.sessionToken};});
  ack(socket,'ROOM_JOIN',async(data)=>{const roomCode=String(data.roomCode??'').toUpperCase();const room=await withRoomLock(roomCode,async current=>{const existing=data.playerId&&current.players.find(p=>p.id===data.playerId&&p.sessionToken===data.sessionToken);if(existing){existing.socketId=socket.id;existing.connected=true;await saveRoom(current);return current;}if(current.phase!=='lobby'||current.players.length>=current.maxPlayers)throw Error('참가할 수 없는 방입니다.');const nickname=String(data.nickname??'').trim().slice(0,16);if(!nickname||current.players.some(p=>p.nickname===nickname))throw Error('사용할 수 없는 닉네임입니다.');const playerId=randomUUID();current.players.push({id:playerId,nickname,sessionToken:token(),socketId:socket.id,connected:true,ready:false,roleConfirmed:false,clueConfirmed:false,character:null,tokens:[],equipment:{shields:[],swords:[],staffs:0,fans:0,quill:false}});current.updatedAt=Date.now();await saveRoom(current);return current;});const me=room.players.find(p=>p.socketId===socket.id)!;bind(socket,room,me.id);await emitRoomState(io,room);return {roomCode:room.roomCode,playerId:me.id,sessionToken:me.sessionToken};});
  const mutate=(name:string,action:(playerId:string,data:any)=>BloodBoundAction)=>ack(socket,name,async data=>{const roomCode=String(data.roomCode??'').toUpperCase();const room=await withRoomLock(roomCode,async current=>{const playerId=session(socket,roomCode);const result=reduce(current,action(playerId,data));if('error'in result)throw Error(result.error);const next=settleBots(result.state);await saveRoom(next);return next;});await emitRoomState(io,room);scheduleBotDecision(io,room);return {};});
  // Readiness is intentionally outside the turn reducer: no rule state is changed here.
  socket.on('PLAYER_READY',async(data:any,callback?: (reply:Ack)=>void)=>{try{const roomCode=String(data.roomCode??'').toUpperCase();const room=await withRoomLock(roomCode,async current=>{const playerId=session(socket,roomCode);if(current.phase!=='lobby')throw Error('대기실에서만 준비할 수 있습니다.');const p=current.players.find(item=>item.id===playerId)!;p.ready=!p.ready;current.updatedAt=Date.now();await saveRoom(current);return current;});await emitRoomState(io,room);callback?.({ok:true,data:{}});}catch(error){const message=error instanceof Error?error.message:'요청을 처리하지 못했습니다.';callback?.({ok:false,error:message});socket.emit('ERROR',{message});}});
  ack(socket,'BOT_FILL',async data=>{const roomCode=String(data.roomCode??'').toUpperCase();const room=await withRoomLock(roomCode,async current=>{const playerId=session(socket,roomCode);if(current.phase!=='lobby'||current.hostId!==playerId)throw Error('방장만 대기실에서 봇을 추가할 수 있습니다.');let number=current.players.filter(player=>player.isBot).length;while(current.players.length<current.maxPlayers){number++;current.players.push({id:randomUUID(),nickname:`가면 봇 ${number}`,sessionToken:'',socketId:null,connected:true,ready:true,roleConfirmed:false,clueConfirmed:false,character:null,tokens:[],equipment:botEquipment(),isBot:true});}current.updatedAt=Date.now();await saveRoom(current);return current;});await emitRoomState(io,room);return {};});
  ack(socket,'BOT_REMOVE',async data=>{const roomCode=String(data.roomCode??'').toUpperCase();const room=await withRoomLock(roomCode,async current=>{const playerId=session(socket,roomCode);if(current.phase!=='lobby'||current.hostId!==playerId)throw Error('방장만 대기실에서 봇을 내보낼 수 있습니다.');current.players=current.players.filter(player=>!player.isBot);current.updatedAt=Date.now();await saveRoom(current);return current;});await emitRoomState(io,room);return {};});
  mutate('GAME_START',(actorId)=>({type:'START',actorId}));mutate('ROLE_CONFIRM',(actorId)=>({type:'ROLE_CONFIRM',actorId}));mutate('CLUE_CONFIRM',(actorId)=>({type:'CLUE_CONFIRM',actorId}));mutate('PASS',(actorId,d)=>({type:'PASS',actorId,targetId:String(d.targetId)}));mutate('ATTACK',(actorId,d)=>({type:'ATTACK',actorId,targetId:String(d.targetId)}));mutate('INTERVENE_OFFER',(actorId)=>({type:'INTERVENE_OFFER',actorId}));mutate('INTERVENE_DECIDE',(actorId,d)=>({type:'INTERVENE_DECIDE',actorId,intervenerId:d.intervenerId?String(d.intervenerId):undefined}));mutate('TOKEN_SELECT',(actorId,d)=>({type:'TOKEN_SELECT',actorId,token:d.token}));mutate('ABILITY_DECIDE',(actorId,d)=>({type:'ABILITY_DECIDE',actorId,use:!!d.use}));mutate('ABILITY_INPUT',(actorId,d)=>({type:'ABILITY_INPUT',actorId,kind:d.kind,targetIds:d.targetIds,choice:d.choice,curses:d.curses}));mutate('HARLEQUIN_ACK',(actorId)=>({type:'HARLEQUIN_ACK',actorId}));
  ack(socket,'GAME_RESTART',async data=>{const roomCode=String(data.roomCode??'').toUpperCase();const room=await withRoomLock(roomCode,async current=>{const playerId=session(socket,roomCode);if(current.hostId!==playerId||current.phase!=='result')throw Error('방장만 새 게임을 시작할 수 있습니다.');current.phase='lobby';current.players=current.players.map(p=>({...p,ready:p.isBot===true,roleConfirmed:false,clueConfirmed:false,character:null,tokens:[],equipment:botEquipment(),curse:undefined}));current.result=undefined;current.attack=undefined;current.pendingAbility=undefined;current.pendingWound=undefined;current.resolutionStack=[];current.publicLog=[];current.privateLog=[];current.harlequinViews={};current.curseDistributed=false;current.updatedAt=Date.now();await saveRoom(current);return current;});await emitRoomState(io,room);return {};});
  socket.on('disconnect',()=>{const roomCode=socket.data.roomCode as string|undefined,playerId=socket.data.playerId as string|undefined;if(!roomCode||!playerId)return;void withRoomLock(roomCode,async room=>{const player=room.players.find(p=>p.id===playerId);if(player&&player.socketId===socket.id){player.connected=false;player.socketId=null;room.updatedAt=Date.now();await saveRoom(room);}return room;}).then(room=>emitRoomState(io,room)).catch(()=>{});});
  ack(socket,'ROOM_LEAVE',async data=>{const roomCode=String(data.roomCode??'').toUpperCase();const room=await withRoomLock(roomCode,async current=>{const playerId=session(socket,roomCode);if(current.phase==='lobby'||current.phase==='result'){current.players=current.players.filter(p=>p.id!==playerId);if(!current.players.length){await deleteRoom(roomCode);return current;}if(current.hostId===playerId)current.hostId=current.players[0]!.id;}else{const leaving=current.players.find(player=>player.id===playerId);if(leaving){leaving.connected=false;leaving.socketId=null;}}current.updatedAt=Date.now();await saveRoom(current);return current;});socket.leave(roomChannel(roomCode));socket.leave(channel(socket.data.playerId));socket.data.roomCode=undefined;socket.data.playerId=undefined;if(room.players.length)await emitRoomState(io,room);return {};});
}
