export const CLIENT_EVENTS = ['ROOM_CREATE','ROOM_JOIN','ROOM_LEAVE','PLAYER_READY','GAME_START','ROLE_CONFIRM','CLUE_CONFIRM','PASS','ATTACK','INTERVENE_OFFER','INTERVENE_DECIDE','TOKEN_SELECT','ABILITY_DECIDE','ABILITY_INPUT','HARLEQUIN_ACK','GAME_RESTART'] as const;
export const SERVER_EVENTS = ['ROOM_STATE','ERROR'] as const;
