export type Suit = 'parrot' | 'map' | 'treasure' | 'jolly';
export type CardKind = 'number' | 'wild' | 'pirate' | 'tigress' | 'skullKing' | 'mermaid' | 'escape' | 'kraken' | 'whale' | 'stingray' | 'davy' | 'con' | 'lastVolley' | 'plank' | 'loot';
export interface Card { id: string; kind: CardKind; suit?: Suit; rank?: number; name: string; isExpansion?: boolean; isZeroFourteen?: boolean; }
export type CardDeclaration = 'pirate' | 'escape' | 0 | 14 | 'parrot' | 'map' | 'treasure';
export type Phase = 'lobby' | 'bidding' | 'play' | 'decision' | 'roundScore' | 'result';
export interface CardOptions { kraken: boolean; whale: boolean; loot: boolean; pirateAbilities: boolean; expansionSuitCards: boolean; wildMonkey: boolean; maryThorne: boolean; lastVolley: boolean; firstMateCon: boolean; stingray: boolean; davyJones: boolean; walkThePlank: boolean; }
export interface GameConfig { maxPlayers: number; advanced: boolean; expansionSuitCards: boolean; roundMode: 'classic' | 'evenKeeled' | 'brawl' | 'swift' | 'broadside' | 'whirlpool' | 'bedtime'; cards?: CardOptions; }
export interface SkullPlayer { id: string; nickname: string; sessionToken: string; socketId: string | null; connected: boolean; ready: boolean; isBot: boolean; hand: Card[]; bid: number | null; tricks: number; score: number; roundBonus: number; rascalBet?: number; forcedCardId?: string; peekedDeck?: Card[]; }
export interface PlayedCard { playerId: string; card: Card; declaration?: CardDeclaration; }
/** The most recently resolved trick, retained long enough for clients to animate it. */
export interface LastTrick { cards: PlayedCard[]; winnerId: string | null; }
export type PendingDecision = { kind: 'rosieLeader'; playerId: string; options: string[] } | { kind: 'bendtDiscard'; playerId: string; remaining: number } | { kind: 'rascalBet'; playerId: string } | { kind: 'harryBid'; playerId: string } | { kind: 'maryTarget'; playerId: string; options: string[] } | { kind: 'lastVolley'; playerId: string } | { kind: 'plankTarget'; playerId: string; options: string[] };
export interface AbilityTask { sourceName: string; ownerId: string; }
export interface RoundRecord { round: number; cards: number; scores: Array<{ playerId: string; bid: number; tricks: number; base: number; bonus: number; total: number }>; }
export interface ChatMessage { id: string; playerId: string; text: string; at: number; }
export interface SkullRoom { roomCode: string; hostId: string; config: GameConfig; players: SkullPlayer[]; phase: Phase; roundIndex: number; schedule: number[]; cardsThisRound: number; dealerIndex: number; leaderId: string | null; turnId: string | null; trick: PlayedCard[]; trickPlayerIds: string[]; trickLead?: Suit | null; lastTrick?: LastTrick; deck: Card[]; lootAlliances: Array<[string, string]>; pendingDecision?: PendingDecision; abilityQueue?: AbilityTask[]; advanceReady: Set<string>; chat: ChatMessage[]; history: RoundRecord[]; log: string[]; createdAt: number; }
export interface PublicPlayer { id: string; nickname: string; connected: boolean; ready: boolean; isBot: boolean; cardsLeft: number; bid: number | null; tricks: number; score: number; }
export interface ClientGameState { roomCode: string; playerId: string; hostId: string; config: GameConfig; phase: Phase; round: number; cardsThisRound: number; dealerId: string | null; leaderId: string | null; turnId: string | null; players: PublicPlayer[]; hand: Card[]; legalCardIds: string[]; trick: PlayedCard[]; trickLead?: Suit | null; lastTrick?: LastTrick; pendingDecision?: PendingDecision; pendingPlayerId?: string; pendingKind?: PendingDecision['kind']; peekedDeck?: Card[]; advanceReady: string[]; chat: ChatMessage[]; history: RoundRecord[]; log: string[]; canAdvance: boolean; }
export interface Ack<T = unknown> { ok: boolean; data?: T; error?: string; }
